version: '3.9'

services:
    server:
        build: .
        image: notes-api-task
        environment:
            PORT: ${PORT}
            DATABASE_HOST: database
            DATABASE_PORT: 5432
            DATABASE_USERNAME: ${POSTGRES_USERNAME}
            DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            DATABASE_NAME: ${APP_DB_NAME}
        depends_on:
            - "database"
        ports:
            - '${PORT}:${PORT}'

    database:
        image: 'postgres'
        restart: always
        environment: 
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            APP_DB_NAME: ${APP_DB_NAME}
            APP_DB_USER: ${APP_DB_USER}
            APP_DB_PASSWORD: ${APP_DB_PASSWORD}
        volumes:
            - .:/docker-entrypoint-initdb.d
        ports: 
            - '${DATABASE_PORT}:5432'